sudo: required
dist: trusty
language: node_js
node_js:
    - "5.8.0"
env:
    - CXX=g++-4.8
addons:
    firefox: latest
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - google-chrome
        packages:
            - g++-4.8
            - google-chrome-stable
before_install:
    - npm cache clean
    - npm update npm@latest -g
    - npm install -g bower grunt-cli codeclimate-test-reporter selenium-standalone nightwatch
install:
    - npm install --save-dev
    - bower install
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - node_modules/selenium-standalone/bin/selenium-standalone install
    - mv nightwatch/configuration/globals.json.dist nightwatch/configuration/globals.json
    - sleep 10
script:
    - grunt test
    - grunt nightwatch --env default
after_script:
    - CODECLIMATE_REPO_TOKEN=6b66bc0cfc18d986b1467f0bedb68fe6f2e4ce7954efa5703ef2d1dfe1b2b2d6 codeclimate < coverage/lcov.info
